/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.AddMeasurementDTO = factory(root.ApiSimca.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AddMeasurementDTO model module.
   * @module model/AddMeasurementDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AddMeasurementDTO</code>.
   * @alias module:model/AddMeasurementDTO
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>AddMeasurementDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddMeasurementDTO} obj Optional instance to populate.
   * @return {module:model/AddMeasurementDTO} The populated <code>AddMeasurementDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('placeId')) {
        obj['placeId'] = ApiClient.convertToType(data['placeId'], 'Number');
      }
      if (data.hasOwnProperty('pollutantIds')) {
        obj['pollutantIds'] = ApiClient.convertToType(data['pollutantIds'], ['Number']);
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Creation date of the measurement
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * Place's id where the measurement is made
   * @member {Number} placeId
   */
  exports.prototype['placeId'] = undefined;
  /**
   * @member {Array.<Number>} pollutantIds
   */
  exports.prototype['pollutantIds'] = undefined;
  /**
   * Creation time of the measurement
   * @member {Date} time
   */
  exports.prototype['time'] = undefined;



  return exports;
}));


