/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.AddUserProfileDTO = factory(root.ApiSimca.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AddUserProfileDTO model module.
   * @module model/AddUserProfileDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AddUserProfileDTO</code>.
   * @alias module:model/AddUserProfileDTO
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>AddUserProfileDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddUserProfileDTO} obj Optional instance to populate.
   * @return {module:model/AddUserProfileDTO} The populated <code>AddUserProfileDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bio')) {
        obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
      }
      if (data.hasOwnProperty('birthday')) {
        obj['birthday'] = ApiClient.convertToType(data['birthday'], 'Date');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'Number');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('profilePicture')) {
        obj['profilePicture'] = ApiClient.convertToType(data['profilePicture'], 'String');
      }
      if (data.hasOwnProperty('timezone')) {
        obj['timezone'] = ApiClient.convertToType(data['timezone'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * Brief user's description
   * @member {String} bio
   */
  exports.prototype['bio'] = undefined;
  /**
   * User's birthday: YYYY-MM-DDTHH:mm:ss.GTM or value in milliseconds
   * @member {Date} birthday
   */
  exports.prototype['birthday'] = undefined;
  /**
   * User's residence
   * @member {Number} country
   */
  exports.prototype['country'] = undefined;
  /**
   * User's lastname
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * User's name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * User profile pictre URL
   * @member {String} profilePicture
   */
  exports.prototype['profilePicture'] = undefined;
  /**
   * Country time zone
   * @member {Number} timezone
   */
  exports.prototype['timezone'] = undefined;
  /**
   * User profile URL
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


