/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.AddValuesToMeasurementDTO = factory(root.ApiSimca.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AddValuesToMeasurementDTO model module.
   * @module model/AddValuesToMeasurementDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AddValuesToMeasurementDTO</code>.
   * @alias module:model/AddValuesToMeasurementDTO
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>AddValuesToMeasurementDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddValuesToMeasurementDTO} obj Optional instance to populate.
   * @return {module:model/AddValuesToMeasurementDTO} The populated <code>AddValuesToMeasurementDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('average')) {
        obj['average'] = ApiClient.convertToType(data['average'], 'Number');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], {'String': 'Number'});
      }
      if (data.hasOwnProperty('pollutantId')) {
        obj['pollutantId'] = ApiClient.convertToType(data['pollutantId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} average
   */
  exports.prototype['average'] = undefined;
  /**
   * @member {Object.<String, Number>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {Number} pollutantId
   */
  exports.prototype['pollutantId'] = undefined;



  return exports;
}));


