/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/PlaceDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PlaceDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.MeasurementDTO = factory(root.ApiSimca.ApiClient, root.ApiSimca.PlaceDTO);
  }
}(this, function(ApiClient, PlaceDTO) {
  'use strict';




  /**
   * The MeasurementDTO model module.
   * @module model/MeasurementDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MeasurementDTO</code>.
   * @alias module:model/MeasurementDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>MeasurementDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MeasurementDTO} obj Optional instance to populate.
   * @return {module:model/MeasurementDTO} The populated <code>MeasurementDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('place')) {
        obj['place'] = PlaceDTO.constructFromObject(data['place']);
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Date');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Creation date of the measurement
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * Autogenerated measurement id
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Place where the measurement is made
   * @member {module:model/PlaceDTO} place
   */
  exports.prototype['place'] = undefined;
  /**
   * Creation time of the measurement
   * @member {Date} time
   */
  exports.prototype['time'] = undefined;
  /**
   * The user who created the measurement
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;



  return exports;
}));


