/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/MeasurementDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MeasurementDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.MeasurementsDTO = factory(root.ApiSimca.ApiClient, root.ApiSimca.MeasurementDTO);
  }
}(this, function(ApiClient, MeasurementDTO) {
  'use strict';




  /**
   * The MeasurementsDTO model module.
   * @module model/MeasurementsDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MeasurementsDTO</code>.
   * @alias module:model/MeasurementsDTO
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>MeasurementsDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MeasurementsDTO} obj Optional instance to populate.
   * @return {module:model/MeasurementsDTO} The populated <code>MeasurementsDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mediciones')) {
        obj['mediciones'] = ApiClient.convertToType(data['mediciones'], [MeasurementDTO]);
      }
    }
    return obj;
  }

  /**
   * List of measurements
   * @member {Array.<module:model/MeasurementDTO>} mediciones
   */
  exports.prototype['mediciones'] = undefined;



  return exports;
}));


