/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/PollutantDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PollutantDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.PollutantsDTO = factory(root.ApiSimca.ApiClient, root.ApiSimca.PollutantDTO);
  }
}(this, function(ApiClient, PollutantDTO) {
  'use strict';




  /**
   * The PollutantsDTO model module.
   * @module model/PollutantsDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PollutantsDTO</code>.
   * @alias module:model/PollutantsDTO
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PollutantsDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PollutantsDTO} obj Optional instance to populate.
   * @return {module:model/PollutantsDTO} The populated <code>PollutantsDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pollutants')) {
        obj['pollutants'] = ApiClient.convertToType(data['pollutants'], [PollutantDTO]);
      }
    }
    return obj;
  }

  /**
   * List of pollutants
   * @member {Array.<module:model/PollutantDTO>} pollutants
   */
  exports.prototype['pollutants'] = undefined;



  return exports;
}));


