/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.PollutantDTO = factory(root.ApiSimca.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PollutantDTO model module.
   * @module model/PollutantDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PollutantDTO</code>.
   * @alias module:model/PollutantDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PollutantDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PollutantDTO} obj Optional instance to populate.
   * @return {module:model/PollutantDTO} The populated <code>PollutantDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('symbol')) {
        obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
      }
      if (data.hasOwnProperty('units')) {
        obj['units'] = ApiClient.convertToType(data['units'], 'String');
      }
    }
    return obj;
  }

  /**
   * Pollutant's description
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Autogenerated pollutant id
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Full name of the pollutant
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Pollutant's symbol
   * @member {String} symbol
   */
  exports.prototype['symbol'] = undefined;
  /**
   * Pollutant's units of measurement
   * @member {String} units
   */
  exports.prototype['units'] = undefined;



  return exports;
}));


