/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/UserProfileDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserProfileDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.UserDTO = factory(root.ApiSimca.ApiClient, root.ApiSimca.UserProfileDTO);
  }
}(this, function(ApiClient, UserProfileDTO) {
  'use strict';




  /**
   * The UserDTO model module.
   * @module model/UserDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserDTO</code>.
   * @alias module:model/UserDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>UserDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDTO} obj Optional instance to populate.
   * @return {module:model/UserDTO} The populated <code>UserDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('profile')) {
        obj['profile'] = UserProfileDTO.constructFromObject(data['profile']);
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
    }
    return obj;
  }

  /**
   * User's email
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * Autogenerated user id
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * User's Profile information
   * @member {module:model/UserProfileDTO} profile
   */
  exports.prototype['profile'] = undefined;
  /**
   * User's state. UNVERIFIED, ACTIVE, INATIVE or BANNED
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Login name in the web and mobile apps
   * @member {String} username
   */
  exports.prototype['username'] = undefined;



  return exports;
}));


