/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/MeasurementDataDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MeasurementDataDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiSimca) {
      root.ApiSimca = {};
    }
    root.ApiSimca.DatacontrollerApi = factory(root.ApiSimca.ApiClient, root.ApiSimca.MeasurementDataDTO);
  }
}(this, function(ApiClient, MeasurementDataDTO) {
  'use strict';

  /**
   * Datacontroller service.
   * @module api/DatacontrollerApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DatacontrollerApi. 
   * @alias module:api/DatacontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getMeasurementPollutantDataUsingGET operation.
     * @callback module:api/DatacontrollerApi~getMeasurementPollutantDataUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MeasurementDataDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getMeasurementPollutantData
     * @param {Number} measurementId measurementId
     * @param {Number} pollutantId pollutantId
     * @param {module:api/DatacontrollerApi~getMeasurementPollutantDataUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MeasurementDataDTO}
     */
    this.getMeasurementPollutantDataUsingGET = function(measurementId, pollutantId, callback) {
      var postBody = null;

      // verify the required parameter 'measurementId' is set
      if (measurementId === undefined || measurementId === null) {
        throw new Error("Missing the required parameter 'measurementId' when calling getMeasurementPollutantDataUsingGET");
      }

      // verify the required parameter 'pollutantId' is set
      if (pollutantId === undefined || pollutantId === null) {
        throw new Error("Missing the required parameter 'pollutantId' when calling getMeasurementPollutantDataUsingGET");
      }


      var pathParams = {
      };
      var queryParams = {
        'measurementId': measurementId,
        'pollutantId': pollutantId
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = MeasurementDataDTO;

      return this.apiClient.callApi(
        '/api/data/v1/data', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
