/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiSimca);
  }
}(this, function(expect, ApiSimca) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiSimca.MeasurementcontrollerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MeasurementcontrollerApi', function() {
    describe('addValuesToMeasurementUsingPOST', function() {
      it('should call addValuesToMeasurementUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addValuesToMeasurementUsingPOST
        //instance.addValuesToMeasurementUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createMeasurementUsingPOST', function() {
      it('should call createMeasurementUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createMeasurementUsingPOST
        //instance.createMeasurementUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMeasurementUsingDELETE', function() {
      it('should call deleteMeasurementUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteMeasurementUsingDELETE
        //instance.deleteMeasurementUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editMeasurementUsingPUT', function() {
      it('should call editMeasurementUsingPUT successfully', function(done) {
        //uncomment below and update the code to test editMeasurementUsingPUT
        //instance.editMeasurementUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMeasurementByIdUsingGET', function() {
      it('should call getMeasurementByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getMeasurementByIdUsingGET
        //instance.getMeasurementByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMeasurementUsingGET', function() {
      it('should call getMeasurementUsingGET successfully', function(done) {
        //uncomment below and update the code to test getMeasurementUsingGET
        //instance.getMeasurementUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
