/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiSimca);
  }
}(this, function(expect, ApiSimca) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiSimca.PollutantcontrollerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PollutantcontrollerApi', function() {
    describe('createPollutantUsingPOST', function() {
      it('should call createPollutantUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createPollutantUsingPOST
        //instance.createPollutantUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePollutantUsingDELETE', function() {
      it('should call deletePollutantUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deletePollutantUsingDELETE
        //instance.deletePollutantUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editPollutantUsingPUT', function() {
      it('should call editPollutantUsingPUT successfully', function(done) {
        //uncomment below and update the code to test editPollutantUsingPUT
        //instance.editPollutantUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPollutantUsingGET', function() {
      it('should call getPollutantUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPollutantUsingGET
        //instance.getPollutantUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPollutantsUsingGET', function() {
      it('should call getPollutantsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPollutantsUsingGET
        //instance.getPollutantsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
