/**
 * API SIMCA
 * SIMCA API Client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pdgsimca@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiSimca);
  }
}(this, function(expect, ApiSimca) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiSimca.UsercontrollerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsercontrollerApi', function() {
    describe('addUserUsingPOST', function() {
      it('should call addUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addUserUsingPOST
        //instance.addUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkEmailConfirmationStatusUsingGET', function() {
      it('should call checkEmailConfirmationStatusUsingGET successfully', function(done) {
        //uncomment below and update the code to test checkEmailConfirmationStatusUsingGET
        //instance.checkEmailConfirmationStatusUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkPasswordResetRequestStatusUsingGET', function() {
      it('should call checkPasswordResetRequestStatusUsingGET successfully', function(done) {
        //uncomment below and update the code to test checkPasswordResetRequestStatusUsingGET
        //instance.checkPasswordResetRequestStatusUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmEmailUsingPUT', function() {
      it('should call confirmEmailUsingPUT successfully', function(done) {
        //uncomment below and update the code to test confirmEmailUsingPUT
        //instance.confirmEmailUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserUsingDELETE', function() {
      it('should call deleteUserUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteUserUsingDELETE
        //instance.deleteUserUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserByUsernameUsingGET', function() {
      it('should call getUserByUsernameUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUserByUsernameUsingGET
        //instance.getUserByUsernameUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserUsingGET', function() {
      it('should call getUserUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUserUsingGET
        //instance.getUserUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersUsingGET', function() {
      it('should call getUsersUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUsersUsingGET
        //instance.getUsersUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestPasswordResetUsingPOST', function() {
      it('should call requestPasswordResetUsingPOST successfully', function(done) {
        //uncomment below and update the code to test requestPasswordResetUsingPOST
        //instance.requestPasswordResetUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetPasswordUsingPUT', function() {
      it('should call resetPasswordUsingPUT successfully', function(done) {
        //uncomment below and update the code to test resetPasswordUsingPUT
        //instance.resetPasswordUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
